<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>052f70c1-8400-4243-9129-8c0e43301fa1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Interfaces\**" />
    <Content Remove="Models\Interfaces\**" />
    <EmbeddedResource Remove="Models\Interfaces\**" />
    <None Remove="Models\Interfaces\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Responses\" />
    <Folder Include="DTOs\Requests\" />
    <Folder Include="Helpers\" />
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Settings\" />
  </ItemGroup>

</Project>
